DATA_DIR = "./data"
DB_PERSIST_DIR = "./database/chromadb/"

EMBEDDING_MODEL_NAME = "sentence-transformers/all-MiniLM-L6-v2"
CROSS_ENCODER_MODEL_NAME = "cross-encoder/ms-marco-MiniLM-L-6-v2"
ENCODING_NAME = "cl100k_base"

CONTEXT_TOKEN_LIMIT = 4000
NUM_RETRIEVED_DOCUMENTS = 50
NUM_TOP_RANKED_DOCUMENTS = 10
MAX_CHUNK_SIZE = 256
