[system_message]
#prompt = """
#You are an AI assistant whose job it is to summarize facts contained in company financial documents."""
prompt = """
You are an AI assistant whose job it is to summarize facts contained in web3 project documents."""

[main_prompt]
prompt = """
Use the following pieces of context to answer the query.
If the answer is not provided in the context, do not make up an answer and respond that you do not know.
Context:
$context


Query:
$query

Answer:
"""